---
- name: "Install aptitude using apt"
  ansible.builtin.apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: "Install required system packages"
  ansible.builtin.apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: "Install GPG Agent"
  ansible.builtin.apt: name=gpg-agent state=latest update_cache=yes

- name: "Add Docker GPG apt Key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker Repository"
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Update apt and install docker-ce"
  ansible.builtin.apt: update_cache=yes name=docker-ce state=latest

- name: "Install Docker Module for Python"
  ansible.builtin.pip:
    name: docker

- name: "Ensure Docker is started"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
